language: java
jdk:
- openjdk8
env:
- NODE_VERSION=12 CC=clang CXX=clang++
before_install:
- nvm install $NODE_VERSION
addons:
  chrome: stable
before_script:
- yarn global add @angular/cli
cache:
  yarn: true
  directories:
  - survey-ui/node_modules
  - .autoconf
  - $HOME/.m2
# only build for commits/pr targeted to master branch
# this avoid duplicate builds for push+PR
branches:
  only:
  - master
script:
- mvn verify jacoco:report
after_success:
- mvn coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: survey-shrike-server
  on:
    repo: anupbaranwal/surveyshrike
